import os, sys

scMINER_PATH = os.environ['scMINER_PATH']
PYTHON_PATH = os.environ['PYTHON_PATH']
sys.path.insert(0, scMINER_PATH)
sys.path.insert(0, PYTHON_PATH)

import argparse
import warnings
import shlex, subprocess
warnings.filterwarnings('ignore', category=Warning)

def setup(args):
	parser = argparse.ArgumentParser(description='Single-cell analysis package.')
	parser.add_argument('module', help='Procedure to select and execute from the package [MIE | MICA]')
	args_ = parser.parse_args(args[1:2])
	return args_

def run(args):
	args_ = setup(args)
	if args_.module == 'MIE':
		# MIE: Based on the running mode number of parameters and the number of executable files generated by the program varies 
		# MIE.py checks on if the command has enough parameters
		script = PYTHON_PATH + ' ' + scMINER_PATH + 'MIE/MIE.py ' + ' '.join(args[2:])
		subprocess.Popen(shlex.split(script))
	elif args_.module == 'MICA':
		# MICA: Based on the running mode the number of parameters and the number of executable files generated by the program varies
		# MICA.py checks on if the command has enough parameters
		script = PYTHON_PATH + ' ' + scMINER_PATH + 'MICA/MICA.py ' + ' '.join(args[2:])
		subprocess.Popen(shlex.split(script))
	else:
		print('[EROR] --> [MAIN] Unsupported command.')
		exit()


if __name__ == '__main__':
	run(sys.argv)
	print('[INFO] --> [MAIN] Finished.')