title: scMINER
remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"
color_scheme: nil
footer_content: "Copyright &copy; 2019- Yu Lab. Distributed by an <a href=\"https://github.com/jyyulab/scMINER/blob/master/LICENSE.txt\">Apache License 2.0.</a>"
search_enabled: true