---
title: scRNA-seq quality control report
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output: html_document
params:
    Obj:
      value: x
    projectName:
      value: x
    plot.dir: 
      value: x
    cfs:
      value: x
    output.cutoff:
      value: x
    group:
      value: x
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 

```


```{r Get_sample_info, echo= FALSE}

cfs<-params$cfs
d<-exprs(params$Obj)
eset<-params$Obj
#calculate basic stastistics
cells_per_gene <- Matrix::rowSums(d!=0)
nGene <- sum(cells_per_gene > 0) # none zero genes
genes_per_cell <- Matrix::colSums(d!=0)
nCell <- sum(genes_per_cell > 0) #none zero cells

M_gene<-floor(median(eset$nGene))
mu_gene<-floor(mean(eset$nGene))
M_UMI<-floor(median(eset$nUMI.total))
mu_UMI<-floor(mean(eset$nUMI.total))

sample_info_c1 <- c("Sample ID", "Output Directory", "Raw Genes", "Raw Cells", "Mean cells per gene")
sample_info_c2 <- c(params$projectName, normalizePath(params$plot.dir), dim(d)[1], dim(d)[2], floor(median(cells_per_gene)))
sample_info <- matrix(c(sample_info_c1, sample_info_c2), ncol = 2, byrow = F)

# plot table
sample_info %>% 
  kable("html") %>% 
  kable_styling(bootstrap_options = "striped", font_size = 14) %>% 
  column_spec(1, bold = T) %>% column_spec(2, color = "red", bold = T)

key_c1 <- c("NonZero Cells", "NonZero Genes", "Median Genes per Cell", "Mean UMIs per Cell")
key_c2 <- c(nCell, nGene, M_gene, mu_UMI)
key_table <- matrix(c(key_c1, key_c2), ncol = 2, byrow = F)

# print quality control report
t(key_table) %>% kable("html", align = "c") %>% 
  kable_styling(bootstrap_options = "striped", font_size = 20) %>% 
  column_spec(1:4, bold = T) %>% 
  row_spec(2, color = "red", background = "lightgreen")

```


### 1. Quality control on genes 
#### 1.1 Calculate and visualize filtering criteria
```{r Gene_qc_report, echo=FALSE}
## 1.1.a Calculate criteria 

gene <- unname((which(cells_per_gene >= cfs$nCell_cutoff)))

# 1.1.b Visulize the distribution of cell counts of each gene
p.gene.qc <- ggplot(data = data.frame(ncells = cells_per_gene), aes(log10(ncells+1))) +
              geom_histogram(bins = 100) +
              theme_classic()+
              labs(x = "Log10 (Cell counts + 1)",
                   y = "Gene counts",
                   title = "Histogram: Number of cells expressed by each genes") +
              theme(
                    axis.text = element_text(size = 10),
                    axis.title = element_text(size = 12, face = "bold"),
                    plot.title = element_text(size = 12, face = "bold"))

if(params$output.cutoff) p.gene.qc <- p.gene.qc +
                      geom_vline(
                      xintercept = log10 (cfs$nCell_cutoff + 1),
                      data = as.data.frame(cfs$nCell_cutoff),
                      color="blue",size = 1,alpha = 0.3)

ggsave(plot = p.gene.qc, filename = "1_1_Gene_QCmetrics_before_filtering.png",
      width = 10, height = 4, units = "in", dpi = 300)

```

```{r, fig.width=10, fig.height=4 ,echo=FALSE} 
p.gene.qc
```


#### 1.2 Generate QC report on genes
```{r Gene_filtering, echo = FALSE}

g_tbl_1 <- c(dim(d)[1], dim(d)[1]-length(gene), length(gene))
perGene_rm <- round((g_tbl_1[2]/g_tbl_1[1] * 100), 2)
g_tbl_2 <- c("100%", paste0(perGene_rm,"%"), paste0(100-perGene_rm,"%"))

gene_table <- matrix(c(g_tbl_1, g_tbl_2), ncol = 2, byrow = F) # generate matrix
rownames(gene_table) <- c("Total Genes", "Unqualified Genes", "Qualified Genes");
colnames(gene_table) <- c("Number", "Percent") #rename

#plot table
gene_table %>% kable("html") %>% 
  kable_styling(bootstrap_options = "striped", font_size = 14) %>% 
  column_spec(2:3, bold = T, color = "Red") %>% 
  add_footnote(paste0("Genes expressed in less than 5% (", 
                      nCell_cutoff, ") cells will be removed."),  
               notation = "number")

```

### 2. Quality control on cells
#### 2.1 Quality control on # gene expressed and umi counts in cells
```{r Cell_qc_a, echo = FALSE, warning=FALSE}
pd<-pData(eset)
p1 <- ggplot(pd,aes_string(x=group,y="nUMI.total",fill=group)) +
      theme_classic()+
      geom_violin(scale="width", na.rm=TRUE)+
      geom_boxplot(width=0.3,outlier.size = 0.25, outlier.stroke = 0.5,fill="white")+
      labs(x=" ",y="nUMI",title="") +
      theme(legend.position="none",plot.title=element_text(size=8))
  if(params$output.cutoff){
    p1<- p1 + geom_hline(yintercept = cfs$umi_cf_lo, data = as.data.frame(cfs$umi_cf_lo),
                 color="blue",size=2,alpha = 0.3) +
              geom_label(aes(1,cfs$umi_cf_lo,label = cfs$umi_cf_lo, vjust = -1),size=3,colour="white")+
              geom_hline(yintercept = cfs$umi_cf_hi, data = as.data.frame(cfs$umi_cf_hi),
                 color="blue",size=2,alpha = 0.3) +
              geom_label(aes(1,cfs$umi_cf_hi,label = cfs$umi_cf_hi, vjust = -1),size=3,colour="white")
    }

p2 <- ggplot(pd,aes_string(x=group, y="nGene",fill=group)) +
      theme_classic()+
      geom_violin(scale="width", na.rm=TRUE)+
      geom_boxplot(width=0.3,outlier.size = 0.25, outlier.stroke = 0.5,fill="white")+
      labs(x=" ",y="nGene",title="") +
      theme_classic()+    
      theme(legend.position="none",plot.title=element_text(size=8))

  if(params$output.cutoff){
      p2 <- p2 + geom_hline(yintercept = cfs$nGene_cf, data = as.data.frame(cfs$nGene_cf),
                 color="blue",size=2,alpha = 0.3) +
                 geom_label(aes(1,cfs$nGene_cf,label = cfs$nGene_cf, vjust = -1),size=3,colour="white")
      }


p.cell.1 <- cowplot::plot_grid(p1,p2,nrow=1,ncol=2)
```

```{r, fig.width=10, fig.height=6 ,echo=FALSE} 
p.cell.1
```

#### 2.2 Quality control on Mito and ERCC genes
```{r Cell_qc_b, echo=FALSE, warning=FALSE}

if(sum(pd$percent.spikeIn)!=0){
 p3 <- ggplot(data=pd, aes(x=nUMI.total,y=percent.spikeIn))+
        geom_point(na.rm=TRUE,size=0.8,alpha=0.5)+
        theme_classic()+ 
        labs(x="nUMI",y="ERCC percentage",
             title="") +
        theme(legend.position="none",plot.title=element_text(size=8))
 if (params$output.cutoff){
    p3 <- p3 + geom_hline(yintercept = cfs$ERCC_cf,data=as.data.frame(cfs$ERCC_cf),
                   size=2,color="blue",alpha = 0.3)+
               geom_text(aes(0.5,cfs$ERCC_cf,label = cfs$ERCC_cf, vjust = -1,hjust=-6),size=3)
    }
}else { 
  text<-"\n  No Spike-in genes detected. \n"
  p3 <- ggplot() + 
        theme_void() +
        annotate("text", x = 4, y = 25, size=5, label = text)+
        labs(x="",y="")
  }

if(sum(pd$nUMI.total)!=0){
  p4 <- ggplot(data=pd, aes(x=nUMI.total,y=percent.mito))+
        geom_point(na.rm=TRUE,size=0.8,alpha=0.5)+
        labs(x="nUMI",y="MT-gene fraction",
             title="") +
        theme_classic()+
        theme(legend.position="none",plot.title=element_text(size=8))
  if (params$output.cutoff){
    p4 <- p4 + geom_hline(yintercept = cfs$mito_cf, data=as.data.frame(cfs$mito_cf),
                   size=2,color="blue",alpha = 0.3)+
          geom_text(aes(0.5,cfs$mito_cf,label = cfs$mito_cf, vjust = -1,hjust=-6),size=3)
    }
}else{  
  text<-"\n  No Mitochondrial genes detected. \n"
  p4 <- ggplot() +
        theme_void() +
        annotate("text", x = 4, y = 25, size=5, label = text)+
        labs(x="",y="")
  }

p.cell.2 <- cowplot::plot_grid(p3,p4,nrow=1,ncol=2)

```

```{r, fig.width=10, fig.height=5 , echo=FALSE} 
p.cell.2
```

### 2.3 Suggested Cutoffs
```{r Calc_cell_cutoff, echo=FALSE,results='asis'}

# gather cutoff information 
para_table_r1 <- c(cfs$nCell_cutoff, cfs$nGene_cf, cfs$umi_cf_lo, 0, 0)
para_table_r2 <- c(Inf, Inf, cfs$umi_cf_hi, paste0((cfs$mito_cf * 100), "%"),paste0((cfs$ERCC_cf * 100), "%"))
para_table <- matrix(c(para_table_r1, para_table_r2), ncol = 5, byrow = T)

colnames(para_table) <- c("# Cells per Gene", "# Identified Genes", "# Identified UMIs", "% Mitochondrial Genes","% SpikeIn Genes")
rownames(para_table) <- c("Low Thresholds", "High Thresholds")

para_table %>% kable("html") %>% 
    kable_styling(bootstrap_options = "striped", font_size = 14) %>% 
    column_spec(1, bold = T)
  

```


