site_name: scMINER
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  analytics:
    gtag: G-ABC123
nav:
  - Home: index.md
  - Installation: install.md
  - Contact: contact.md
  - Tutorials:
    - 'Basic analysis on PBMC (14k)': tutorials/PBMC-14k.md
    - 'KO vs. WT analysis on CD8+ T cells': tutorials/CD8T.md
    - 'Mutual information-based clustering analysis (MICA)': tutorials/MICA-advanced.md
    - 'Network visualization': tutorials/network-visualize.md
    - 'Driver target function analysis': tutorials/function-analysis.md
    - 'Activity based clustering': tutorials/activity-based-clustering.md
    - 'Interoperability between SparseEset, Seurat, and anndata': tutorials/interoperability.md
    - 'Data references': tutorials/data-reference.md
repo_url: https://github.com/jyyulab/scMINER
site_author: Liang (Adam) Ding, Hao Shi
copyright: Apache License (Version 2.0)
