#' Raw count matrix of PBMC14k dataset
#'
#' This dataset contains the raw UMI counts of 14,000 Peripheral Blood Mononuclear Cells (PBMCs) of 7 known cell types, with 2,000 cell each.
#'
#' @format ## `pbmc14k_rawCount`
#' A large dgCMatrix with 17,986 rows and 14,000 columns:
#' \describe{
#'   \item{CACTTTGACGCAAT}{UMI counts of all genes of the cell "CACTTTGACGCAAT"}
#'   \item{GTTACGGAAACGAA}{UMI counts of all genes of the cell "GTTACGGAAACGAA"}
#'   \item{AGTCACGACAGGAG}{UMI counts of all genes of the cell "AGTCACGACAGGAG"}
#'   ...
#' }
#' @source A subset of Filtered_DownSampled_SortedPBMC_data.csv from <https://zenodo.org/record/3357167#.YhQNF2RKj6V>
"pbmc14k_rawCount"


#' SparseEset object of PBMC14k dataset
#'
#' This dataset contains the SparseEset object of PBMC14k dataset. For demonstration purposes, it has been downsampled to 3.5k cells, with 500 cells per population.
#'
#' @format ## `pbmc14k_expression.eset`
#' A large dgCMatrix with 17,986 rows and 14,000 columns:
#' \describe{
#'   This data set provides the SparseEset object of PBMC14k dataset that has been filtered, normalized, clustered and annotated.
#' }
#' @source It's generated by scMINER from Filtered_DownSampled_SortedPBMC_data.csv from <https://zenodo.org/record/3357167#.YhQNF2RKj6V>
"pbmc14k_expression.eset"
