#' Raw count matrix of PBMC14k dataset
#'
#' This dataset contains the raw UMI counts of 14,000 Peripheral Blood Mononuclear Cells (PBMCs) of 7 known cell types, with 2,000 cell each.
#'
#' @format ## `pbmc14k_rawCount`
#' A large dgCMatrix with 17,986 rows and 14,000 columns:
#' \describe{
#'   \item{CACTTTGACGCAAT}{UMI counts of all genes of the cell "CACTTTGACGCAAT"}
#'   \item{GTTACGGAAACGAA}{UMI counts of all genes of the cell "GTTACGGAAACGAA"}
#'   \item{AGTCACGACAGGAG}{UMI counts of all genes of the cell "AGTCACGACAGGAG"}
#'   ...
#' }
#' @source A subset of Filtered_DownSampled_SortedPBMC_data.csv from <https://zenodo.org/record/3357167#.YhQNF2RKj6V>
"pbmc14k_rawCount"

#' True label of known cell types for PBMC14k dataset
#'
#' This dataset contains the true label of known cell types of 14,000 Peripheral Blood Mononuclear Cells (PBMCs) in PBMC14k dataset.
#'
#' @format ## `pbmc14k_trueLabel`
#' A data frame with 14,000 rows and 2 columns:
#' \describe{
#'   \item{cell_barcode}{barcodes of cells}
#'   \item{true_label}{true label cell types of cells}
#' }
#' @source A subset of Labels.csv from <https://zenodo.org/record/3357167#.YhQNF2RKj6V>
"pbmc14k_trueLabel"

#' MICA output for PBMC14k dataset
#'
#' This is an example of clustering label file for PBMC14k dataset generated by MICA.
#'
#' @format ## `pbmc14k_MICAoutput`
#' A data frame with 13,605 rows and 4 columns:
#' \describe{
#'   \item{ID}{barcodes of cells}
#'   \item{X}{coordinates of x-axis, usually UMAP_1 or tSNE_1}
#'   \item{Y}{coordinates of y-axis, usually UMAP_2 or tSNE_2}
#'   \item{label}{labels of predicted clusters by MICA}
#' }
#' @source generated by MICA
"pbmc14k_MICAoutput"

#' Signature table of 7 known cell types of PBMC14k dataset
#'
#' This dataset contains the self-curated markers of 7 known cell types of PBMC14k dataset
#'
#' @format ## `pbmc14k_signatureTable`
#' A data frame with 31 rows and 3 columns:
#' \describe{
#'   \item{signature_name}{name of signatures/cell types}
#'   \item{signature_feature}{genes/features of corresponding signatures}
#'   \item{weight}{weight of each feature for corresponding signature, ranging from -1 to 1}
#' }
#' @source Self-curated from multiple sources
"pbmc14k_signatureTable"
